/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rentautos;

import com.sun.java_cup.internal.runtime.Symbol;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KYC
 */
public class JdbuscarReserva extends javax.swing.JDialog {

    String url = "jdbc:odbc:RentAutos";
    DefaultTableModel dfm = new DefaultTableModel();

    /**
     * Creates new form JdbuscarReserva
     */
    public JdbuscarReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBuscar = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtBuscarCedula = new javax.swing.JTextField();
        btnMosTodos = new javax.swing.JButton();
        lblCedula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(0), "Buscar", 2, 1, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(51, 0, 153))); // NOI18N

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jtBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtBuscar);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jButton3.setText("Nueva Busqueda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnMosTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mostrar todos (2).png"))); // NOI18N
        btnMosTodos.setText("Mostrar todos");
        btnMosTodos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMosTodos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMosTodos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnMosTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMosTodosActionPerformed(evt);
            }
        });

        lblCedula.setText("Cedula Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMosTodos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCedula)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMosTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Limpiar() {

        this.txtBuscarCedula.setText("");
        this.txtBuscarCedula.requestFocus();
        this.dfm.setNumRows(0);
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String bus;

        bus = this.txtBuscarCedula.getText();
        String v[] = {"Nombre", "Cedula", "Codigo Reserva", "Fecha Recoleccion", "Fecha Devolucion", "Placa Auto"};
        //DefaultTableModel dfm=new DefaultTableModel(null, v);
        dfm = null;
        dfm = new DefaultTableModel(null, v);
        try {
            Connection con = DriverManager.getConnection(url, "sa", "93102908528");
            PreparedStatement pst = con.prepareStatement("BuscarReserva '" + bus + "'");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                v[0] = rs.getString(1);
                v[1] = rs.getString(2);
                v[2] = rs.getString(3);
                v[3] = rs.getString(4);
                v[4] = rs.getString(5);
                v[5] = rs.getString(6);
                dfm.addRow(v);
            }
            this.jtBuscar.setModel(dfm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la conexion" + e);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String ced;
        int v;
        v = this.jtBuscar.getSelectedRow();
        if (v >= 0) {
            JdReserva.txtCedula.setText(this.jtBuscar.getValueAt(v, 0).toString());
            
            JdReserva.lblNombre.setVisible(true);
            JdReserva.lblApellido.setVisible(true);
            JdReserva.lblDireccion.setVisible(true);
            JdReserva.lblTelefono.setVisible(true);
            JdReserva.lblNumero.setVisible(true);
            JdReserva.lblCodSeg.setVisible(true);
            JdReserva.cbTipoTarjeta.setVisible(true);
            JdReserva.txtNombre.setVisible(true);
            JdReserva.txtApellido.setVisible(true);
            JdReserva.txtDireccion.setVisible(true);
            JdReserva.txtTelefono.setVisible(true);
            JdReserva.txtNumero.setVisible(true);
            JdReserva.txtCodSeg.setVisible(true);
            try {
            ced = this.txtBuscarCedula.getText();
            Connection con = DriverManager.getConnection(url, "sa", "93102908528");
            PreparedStatement pst = con.prepareStatement("BuscarReserva_Cliente '"+ced+"'");
            ResultSet rs = pst.executeQuery();
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            
            if(rs.next()){
                JdReserva.txtCodReserva.setText(String.valueOf(rs.getInt(1)));
                JdReserva.txtCedula.setText(rs.getString(2));
                JdReserva.txtPlaca.setText(rs.getString(3));
                JdReserva.jdateFechaReco.setDate(sdf.parse(rs.getString(4)));
                JdReserva.jdateFechaDevo.setDate(sdf.parse(rs.getString(5)));
                JdReserva.txtTotal.setText(String.valueOf(rs.getFloat(7)));
                JdReserva.txtCantidadDias.setText(String.valueOf(rs.getInt(9)));
                
                String tipoAuto = rs.getString(10);
                
                for (int i = 0; i < JdReserva.cbTipoAuto.getItemCount(); i++) {
                    System.out.println(JdReserva.cbTipoAuto.getItemAt(i).toString());
                    System.out.println(tipoAuto);
                    if(JdReserva.cbTipoAuto.getItemAt(i).toString().equals(tipoAuto.trim())){
                        JdReserva.cbTipoAuto.setSelectedIndex(i);
                        break;
                    }
                }
                
                JdReserva.txtDisponible.setText(String.valueOf(rs.getInt(11)));
                JdReserva.txtCostoDia.setText(String.valueOf(rs.getInt(12)));
                JdReserva.txtNombre.setText(rs.getString(14));
                JdReserva.txtApellido.setText(rs.getString(15));
                JdReserva.txtDireccion.setText(rs.getString(16));
                JdReserva.cbTipoTarjeta.setSelectedItem(rs.getString(17));
                JdReserva.txtNumero.setText(String.valueOf(rs.getInt(18)));
                JdReserva.txtCodSeg.setText(String.valueOf(rs.getInt(19)));
                JdReserva.txtTelefono.setText(String.valueOf(rs.getInt(20)));
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error en la conexion" + e);
        }
            this.dispose();
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnMosTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMosTodosActionPerformed
        String v[] = {"cedCliente", "nomCliente", "apCliente", "dirCliente", "telCliente", "tipoTarjeta", "numTarjeta", "codSegTarjeta"};
        DefaultTableModel dfm = new DefaultTableModel(null, v);
        try {
            Connection con = DriverManager.getConnection(url, "sa", "z");
            PreparedStatement pst = con.prepareStatement("MostrarTodosClientes");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                v[0] = rs.getString(1);
                v[1] = rs.getString(2);
                v[2] = rs.getString(3);
                v[3] = rs.getString(4);
                v[4] = rs.getString(5);
                v[5] = rs.getString(6);
                v[6] = rs.getString(7);
                v[7] = rs.getString(8);

                dfm.addRow(v);
            }
            this.jtBuscar.setModel(dfm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la conexion" + e);
        }

    }//GEN-LAST:event_btnMosTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdbuscarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdbuscarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdbuscarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdbuscarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdbuscarReserva dialog = new JdbuscarReserva(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMosTodos;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtBuscar;
    private javax.swing.JLabel lblCedula;
    public javax.swing.JTextField txtBuscarCedula;
    // End of variables declaration//GEN-END:variables
}
