
package rentautos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class JdBuscarConductor extends javax.swing.JDialog {
    String url="jdbc:odbc:RentAutos";
    DefaultTableModel dfm=new DefaultTableModel();
    /**
     * Creates new form JdBuscarConductor
     */
    public JdBuscarConductor(java.awt.Frame parent, boolean modal) {
        
        initComponents();
        setModal(modal);
    }

    private JdBuscarConductor() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void Limpiar(){
         
         this.txtBuscarCond.setText("");
         this.txtBuscarCond.requestFocus();
         this.dfm.setNumRows(0);
    }
                 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBusCond = new javax.swing.JButton();
        rbnomCon = new javax.swing.JRadioButton();
        rbcedCon = new javax.swing.JRadioButton();
        txtBuscarCond = new javax.swing.JTextField();
        btnMosTodosCond = new javax.swing.JButton();
        btnBusNueCond = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtBusCond = new javax.swing.JTable();

     

        btnBusCond.setText("Buscar");
        btnBusCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusCondActionPerformed(evt);
            }
        });

        rbnomCon.setText("Nombre");
        rbnomCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbnomConMouseClicked(evt);
            }
        });
        rbnomCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnomConActionPerformed(evt);
            }
        });

        rbcedCon.setText("Codigo");
        rbcedCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbcedConMouseClicked(evt);
            }
        });
        rbcedCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcedConActionPerformed(evt);
            }
        });

        btnMosTodosCond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mostrar todos (2).png"))); // NOI18N
        btnMosTodosCond.setText("Mostrar todos");
        btnMosTodosCond.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMosTodosCond.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMosTodosCond.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnMosTodosCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMosTodosCondActionPerformed(evt);
            }
        });

        btnBusNueCond.setText("Nueva Busqueda");
        btnBusNueCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusNueCondActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        JtBusCond.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JtBusCond.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtBusCondMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JtBusCond);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBusNueCond)
                        .addGap(157, 157, 157)
                        .addComponent(jButton4)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbcedCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBusCond)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarCond))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbnomCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMosTodosCond)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(rbcedCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbnomCon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBusCond)
                            .addComponent(txtBuscarCond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMosTodosCond)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBusNueCond)
                    .addComponent(jButton4))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusCondActionPerformed
        String bus;
        if(this.rbcedCon.isSelected()){
            bus=this.txtBuscarCond.getText();
            String v[]={"Cedula","Nombre","Apellido","Direccion","Teléfono","Numero Licencia","Categoria"};
            //DefaultTableModel dfm=new DefaultTableModel(null, v);
            dfm=null;
            dfm=new DefaultTableModel(null, v);
            try {
                Connection con=DriverManager.getConnection(url,"sa","93102908528");
                PreparedStatement pst=con.prepareStatement("BuscarConductor '" + bus +"'," +null);
                ResultSet rs=pst.executeQuery();
                while (rs.next()){
                    v[0]=rs.getString(1).trim();
                    v[1]=rs.getString(2).trim();
                    v[2]=rs.getString(3).trim();
                    v[3]=rs.getString(4).trim();
                    v[4]=rs.getString(5).trim();
                    v[5]=rs.getString(6).trim();
                    v[6]=rs.getString(7).trim();
                    dfm.addRow(v);
                }
                this.JtBusCond.setModel(dfm);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error en la conexion"+e);
            }
        }else{
            bus=this.txtBuscarCond.getText();
            String v[]={"Cedula","Nombre","Apellido","Direccion","Teléfono","Numero Licencia","Categoria"};
            //DefaultTableModel dfm=new DefaultTableModel(null, v);
            dfm=null;
            dfm=new DefaultTableModel(null, v);
            try {
                Connection con=DriverManager.getConnection(url,"sa","93102909528");
                PreparedStatement pst=con.prepareStatement("BuscarConductor "+null+",'" + bus +"'");
                ResultSet rs=pst.executeQuery();
                while (rs.next()){
                    v[0]=rs.getString(1).trim();
                    v[1]=rs.getString(2).trim();
                    v[2]=rs.getString(3).trim();
                    v[3]=rs.getString(4).trim();
                    v[4]=rs.getString(5).trim();
                    v[5]=rs.getString(6).trim();
                    v[6]=rs.getString(7).trim();
                    v[7]=rs.getString(8).trim();

                    dfm.addRow(v);
                }
                this.JtBusCond.setModel(dfm);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error en la conexion"+e);
            }

        }
    }//GEN-LAST:event_btnBusCondActionPerformed

    private void rbnomConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbnomConMouseClicked
        this.txtBuscarCond.setEnabled(true);
        this.txtBuscarCond.setText("");
        this.txtBuscarCond.requestFocus();
    }//GEN-LAST:event_rbnomConMouseClicked

    private void rbcedConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbcedConMouseClicked
        this.txtBuscarCond.setEnabled(true);
        this.txtBuscarCond.setText("");
        this.txtBuscarCond.requestFocus();
    }//GEN-LAST:event_rbcedConMouseClicked

    private void rbcedConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcedConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcedConActionPerformed

    private void btnMosTodosCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMosTodosCondActionPerformed
        String v[]={"Cedula","Nombre","Apellido","Direccion","Teléfono","Numero Licencia","Categoria"};
        DefaultTableModel dfm=new DefaultTableModel(null, v);
        try {
            Connection con=DriverManager.getConnection(url,"sa","93102908528");
            PreparedStatement pst=con.prepareStatement("MostrarTodosConductores");
            ResultSet rs=pst.executeQuery();
            while (rs.next()){
                v[0]=rs.getString(1).trim();
                v[1]=rs.getString(2).trim();
                v[2]=rs.getString(3).trim();
                v[3]=rs.getString(4).trim();
                v[4]=rs.getString(5).trim();
                v[5]=rs.getString(6).trim();
                v[6]=rs.getString(7).trim();

                dfm.addRow(v);
            }
            this.JtBusCond.setModel(dfm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la conexion"+e);
        }
    }//GEN-LAST:event_btnMosTodosCondActionPerformed

    private void btnBusNueCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusNueCondActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnBusNueCondActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void JtBusCondMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtBusCondMouseClicked
        int row=this.JtBusCond.getSelectedRow();
        if (row >= 0) {

            JdRegCond.txtCedConductor.setText(this.JtBusCond.getValueAt(row, 0).toString());
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null,"Seleccione Regristro" );
        }
    }//GEN-LAST:event_JtBusCondMouseClicked

    private void rbnomConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnomConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnomConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdBuscarConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdBuscarConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdBuscarConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdBuscarConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JdBuscarConductor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable JtBusCond;
    private javax.swing.JButton btnBusCond;
    private javax.swing.JButton btnBusNueCond;
    private javax.swing.JButton btnMosTodosCond;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbcedCon;
    private javax.swing.JRadioButton rbnomCon;
    public javax.swing.JTextField txtBuscarCond;
    // End of variables declaration//GEN-END:variables
}
